defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/nlp-models

version: 2
jobs:
  setup_and_run_checks:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Cloning latest and AllenNLP and updating shared configs
          command: |
            git clone --depth=1 --branch=master https://github.com/allenai/allennlp.git allennlp
            rm -rf allennlp/.git
            cp allennlp/.pylintrc ./

      - restore_cache:
          name: Restoring dependencies cache
          keys:
            - deps-v1-{{ checksum "allennlp/requirements.txt" }}-{{ checksum "additional_requirements.txt" }}
            - deps-v1-

      - run:
          name: Installing dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r allennlp/requirements.txt
            pip install -r additional_requirements.txt

      - save_cache:
          name: Saving dependencies cache
          key: deps-v1-{{ checksum "allennlp/requirements.txt" }}-{{ checksum "additional_requirements.txt" }}
          paths:
            - venv

      - run:
          name: Running check scripts
          command: |
            . venv/bin/activate
            make check-scripts

      - run:
          name: Running code linters
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: Running type checks
          command: |
            . venv/bin/activate
            make typecheck

      - run:
          name: Running unit tests
          command: |
            . venv/bin/activate
            make unit-test

      - run:
          name: Submitting coverage report
          command: |
            . venv/bin/activate
            codecov

workflows:
  version: 2
  test:
    jobs:
      - setup_and_run_checks
  nightly:
    jobs:
      - setup_and_run_checks
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
